Fix Duplicate Scenario Runs
cabbage-ex/cabbage pull request #41
Opened 2017-09-13 09:53 UTC by rawkode

List comprehension was creating a cartesian product of both subjects. Going with primitive increment

Closes #40

2017-09-15 02:45 UTC, mgwidmann commented on lib/cabbage/feature.ex
> +      test_number = test_number + 1
does this work? I thought immutability put a damper in these kind of things... is this just rebinding over and over again?

2017-09-15 02:52 UTC, mgwidmann commented on lib/cabbage/feature.ex
> +      test_number = test_number + 1
Doesnt seem like it works in the shell

```elixir
iex(2)> i = 0
0
iex(3)> for x <- 1..10 do
...(3)>   i = i + 1
...(3)>   IO.puts i
...(3)> end
1
1
1
1
1
1
1
1
1
1
[:ok, :ok, :ok, :ok, :ok, :ok, :ok, :ok, :ok, :ok]
```

This looks to be what you want:
```elixir
iex(4)> 100..110 |> Enum.with_index() |> Enum.each(fn {item, index} -> IO.puts index end)
0
1
2
3
4
5
6
7
8
9
10
:ok
```
So you should so something like: (untested)
```elixir
Enum.with_index(scenarios) |> Enum.each(fn {scenario, test_number} ->
   # all the rest of the stuff here
end)
```

2017-09-15 11:51 UTC, rawkode commented
Ah, because the rebinding is within the `for` context, I guess?

Your syntax is much cleaner, I wasn't aware of `Enum.with_index`. I'll adapt.

Thanks for the tips, @mgwidmann

2017-09-16 07:42 UTC, rawkode commented
Sorry for the delay, but back with you now, @mgwidmann

2017-09-26 03:04 UTC, mgwidmann requested changes

2017-09-26 03:04 UTC, mgwidmann commented on lib/cabbage/feature.ex
> +    Enum.with_index(scenarios) |> Enum.each(fn {scenario, test_number} ->
missing the closing `(` or delete this one... this doesn't compile

2017-10-09 18:12 UTC, rawkode commented
@mgwidmann It would be great to get this merged, please :+1: 

Assuming I've not made a mess of it again :joy:

2017-10-17 01:22 UTC, mgwidmann approved these changes

2017-10-17 01:22 UTC, merged

2017-10-17 01:22 UTC, mgwidmann commented
Sorry I missed this! Out of curiosity, why'd you flip the number and the scenario name?

2017-10-17 02:05 UTC, mgwidmann commented
Released in `v0.3.4`!

2017-10-17 13:36 UTC, mgwidmann commented
Sorry I've had to pull version `0.3.4` because it isnt actually running any tests. In the before compile, the `for` loop used to return the quoted code but `Enum.each` does not which means no code is actually injected at compile time. To fix it, it should be an `Enum.map`, but then all the tests fail with an error like:

```
** (UndefinedFunctionError) function Cabbage.DataTableTest."test 0. Data table represented as a list of maps test Data table represented as a list of maps (0) Data table represented as a list of maps"/1 is undefined or private. Did you mean one of:

           * "test Data table represented as a list of maps (0) Data table represented as a list of maps"/1
```

I can try to look into it tonight, but I don't have time at the moment.

2017-10-19 18:32 UTC, rawkode commented
@mgwidmann How do we add a test that verifies the quote test is correct?